Prepared clone yii2 project based on quick-create-yii2-project.

diff --git a/quick-clone-yii2-project b/quick-clone-yii2-project
--- a/quick-clone-yii2-project
+++ b/quick-clone-yii2-project
@@ -1,3 +1,253 @@
 #!/bin/bash
 
- 
+# SETTINGS
+# =======================================================
+
+# Repository
+REPO_TYPE='git|svn'
+REPO_URL=''
+REPO_USER=''
+REPO_PASS=''
+REPO_EMAIL=''
+REPO_DIR=''
+
+# Repository branch
+DEV_BRANCH='master'
+
+# Privilage for Directory - chown
+RIGHTS="${USER}:www-data"
+
+# Yii2
+ENV='Development'
+
+# Hosts
+HOSTS=('frontend.loc' 'frontend/web/' 'backend.loc' 'backend/web/')
+
+# Create DB
+DB_CREATE=true
+DB_HOST='localhost'
+DB_ROOT_PASS=''# Repository branch
+DEV_BRANCH='master'
+
+# Privilage for Directory - chown
+RIGHTS="${USER}:www-data"
+
+# Yii2
+ENV='Development'
+
+# Hosts
+HOSTS=('frontend.loc' 'frontend/web/' 'backend.loc' 'backend/web/')
+
+# Create DB
+DB_CREATE=true
+DB_HOST='localhost'
+DB_ROOT_PASS=''
+
+# DB
+DB_HOST=''
+
+# constants
+# =======================================================
+APACHE2_SITES_PATH=/etc/apache2/sites-available
+
+# Clones repository
+function clone_repository()
+{
+
+  # --- GIT -------------------------------
+  if [[ "$REPO_TYPE" == "git" ]]; then
+
+    regexHttps='(https)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'
+    regexHttp='(http)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'
+
+    if [[ $REPO_URL =~ $regexHttps ]]; then
+
+      url="https://$REPO_USER:$REPO_PASS@${REPO_URL:8}"
+      git clone $url
+
+    elif [[ $REPO_URL =~ $regexHttp ]]; then
+
+      url="http://$REPO_USER:$REPO_PASS@${REPO_URL:8}"
+      git clone $url
+
+    else
+
+      echo 'Repo url isnt valid.'
+
+    fi
+
+  # --- SVN -------------------------------
+  elif [[ "$REPO_TYPE" == "svn" ]]; then
+
+    echo 'SVN isnt implemented'
+    exit 128
+
+  # --- REPO ERROR -------------------------------
+  else
+
+    echo 'Not correct repository type.'
+    exit 128
+
+  fi
+}
+
+# Adds domain to /etc/hosts
+# $1 - string - domain
+function add2hosts
+{
+	sudo sh -c "echo \"127.0.0.1 ${1} www.${1}\" >> /etc/hosts"
+}
+
+# Adds domain to apache2 sites
+# $1 - string - domain
+# $2 - string - path to root
+# $3 - string - path to apache_logs directory
+function add2apache
+{
+
+	read -r -d '' vhosts << EOM
+
+<VirtualHost *:80>
+        # The ServerName directive sets the request scheme, hostname and port that
+        # the server uses to identify itself. This is used when creating
+        # redirection URLs. In the context of virtual hosts, the ServerName
+        # specifies what hostname must appear in the request's Host: header to
+        # match this virtual host. For the default virtual host (this file) this
+        # value is not decisive as it is used as a last resort host regardless.
+        # However, you must set it for any further virtual host explicitly.
+        ServerName www.${1}
+        ServerAlias ${1}
+
+        DocumentRoot ${2}
+
+        <Directory "${2}">
+                Options Indexes FollowSymLinks Includes ExecCGI
+                AllowOverride All
+                Require all granted
+                Allow from all
+        </Directory>
+
+        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
+        # error, crit, alert, emerg.
+        # It is also possible to configure the loglevel for particular
+        # modules, e.g.
+        #LogLevel info ssl:warn
+
+        ErrorLog ${3}/${1}-error.log
+        CustomLog ${3}/${1}-access.log combined
+
+        # For most configuration files from conf-available/, which are
+        # enabled or disabled at a global level, it is possible to
+        # include a line for only one particular virtual host. For example the
+        # following line enables the CGI configuration for this host only
+        # after it has been globally disabled with "a2disconf".
+        #Include conf-available/serve-cgi-bin.conf
+</VirtualHost>
+
+# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
+
+EOM
+
+	sudo sh -c "echo \"${vhosts}\" >> ${APACHE2_SITES_PATH}/${1}.conf"
+	sudo sh -c "a2ensite ${1}"
+
+}
+
+# Adds sites to apache2
+# Use attributes form `project.cfg` file.
+function add_sites()
+{
+  for (( i=0; i<${#HOSTS[@]} ; i+=2 )) ;
+  do
+
+    domain=${HOSTS[i]}
+    path=${HOSTS[i+1]}
+
+    add2hosts $domain
+    add2apache $domain $(pwd)/$REPO_DIR/$path $(pwd)/apache_logs
+
+  done
+}
+
+# Creates project
+# Use attributes from `project.cfg` file.
+function create_project()
+{
+
+  clone_repository
+  cd ./$REPO_DIR
+  php init --env=${ENV} --overwrite=All
+  cd ..
+
+  mkdir apache_logs dumps auths
+
+  # set rights for repo_directory
+  sudo chown -R $RIGHTS $REPO_DIR apache_logs
+
+  add_sites
+
+}
+
+# Runs clone/create repository
+# Use attributes from `project.cfg` file.
+function doit()
+{
+  # load cfg settings
+  # ========================================================
+  if [[ -e "./project.cfg" ]]; then
+    source "./project.cfg"
+    clone_project
+  else
+    echo 'Cannot find project.cfg file.'
+    exit 128
+  fi
+}
+
+# Sets global script variables by flags/attributes
+# $@ - array - flags/attributes
+function attrs()
+{
+  while [[ $# > 0 ]]
+  do
+    key="$1"
+    case $key in
+      -c|--config)
+        g_mode='CONFIG'
+      ;;
+      -h|--help)
+				cat add_domain.md
+				exit
+			;;
+      -U|--user)
+        g_user="$2"
+        shift # past argument
+      ;;
+			-di|--dir)
+      	g_dir="$2"
+      	shift # past argument=value
+      ;;
+			-do|--doit)
+        g_mode='DOIT'
+				domains="$2"
+				shift # past argument
+			;;
+      *)
+        # unknown option
+      ;;
+    esac
+    shift # past argument or value
+  done
+}
+
+# Runs script
+function run()
+{
+  if [[ "$g_mode" == "CONFIG" ]]; then
+    generate_config
+  elif [[ "$g_mode" == "DOIT" ]]; then
+    doit
+  fi
+}
+
+attrs $@
+run
